[package]
name = "papr"
version = "0.1.0"
edition = "2021"

[lib]
name = "papr"

[workspace]
members = ["papr-playground", "papr-python"]

[dependencies]
cpal = { version = "0.15.3", features = ["jack"] }
itertools = "0.13.0"
log = "0.4.22"
petgraph = "0.6.5"

[[example]]
name = "demo"
path = "examples/demo.rs"

[dev-dependencies]
env_logger = "0.11"
hound = "3.5"
