[package]
name = "papr-python"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "papr"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
papr = { path = "../" }
